name: family_home_manager
description: 家庭物品管理与盘库 App
publish_to: "none"
version: 0.5.0+5

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
